#!/bin/bash
#g++ -g -O3 $* -I../include ../src/Factor.cpp ../src/graphmodel.cpp ../src/BPinterface.cpp ../src/test_interface.cpp -lboost_program_options --static 

# No optimization
g++ -g $* -I../include ../src/Factor.cpp ../src/graphmodel.cpp ../src/BPinterface.cpp ../src/test_interface.cpp -lboost_program_options --static -o bp_interface
