#!/bin/bash

javac -d . ../test_build/src/beliefPropagation.java 
javah -jni -d ../include -jni bp_interface

g++ -shared -fPIC -I/usr/local/share/jdk1.8.0_25/include/linux  -I/usr/local/share/jdk1.8.0_25/include/ -I../include -o ../test_build/resource/libBP.so   ../src/libBP.cpp
