#!/bin/bash

#make solve_uai
#make bp_interface

# Run uai solver
#x./uai_14 -f ../data/test.uai -e none.e -T PR

# Run bp_interface
./bp_interface -f ../data/test.uai -e ../data/evid.uai -T PR --verbose

