/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bp_interface */

#ifndef _Included_bp_interface
#define _Included_bp_interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bp_interface
 * Method:    doBP
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_bp_1interface_doBP
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bp_interface
 * Method:    getSolution
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bp_1interface_getSolution
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
